export const client_id_api = "667obVfeDMSyVGN7t3RsIvVbKYjJuOOdbZegcMKA"
export const client_secret_api = "e3T86jxIxlSYwhPdJD4PqCgn6IjRXpLOHy20SHjg2Loxpa20eJvXyjziCFRIhZdctDJW98WvRNP8ECSWQMavDO8V15zhJb1QQaNrHIGaHgnNZirIJU2aw0jjJwBRURRR"
export const azuze_map_primary_key_api = "FaqJhLIckgPjz6XjhcxZfxsRukcyNyZhHJzRZ8H3eMlo4sISPeilJQQJ99AIACYeBjF6AxJHAAAgAZMPFtxq"